<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2017 phpjm.net All Rights Reserved.
*/
if (!defined("ADDECEDEBC")){define("ADDECEDEBC", __FILE__);global $€,$™,$’œˆ,$„—,$™“‘,$””‚,$ž„‘Ÿ—Ž,$Ž——‰ƒ”,$’ˆ“€ƒ‚—,$Ÿ˜‡€Œ™„‹ž—,$ŠŸŽ™Ž†‰Ÿ“ƒ,$“†•›Žšˆ’’ˆ‹,$šŠ™“„’†‘–ˆ,$“œ†„Ž’…‰’,$•’œ€†š€–Ÿ“ž„•,$™…’Œ…“Š‚ž†Œ€‡;function € ($€ ,$™ =""){global $€,$™,$’œˆ,$„—,$™“‘,$””‚,$ž„‘Ÿ—Ž,$Ž——‰ƒ”,$’ˆ“€ƒ‚—,$Ÿ˜‡€Œ™„‹ž—,$ŠŸŽ™Ž†‰Ÿ“ƒ,$“†•›Žšˆ’’ˆ‹,$šŠ™“„’†‘–ˆ,$“œ†„Ž’…‰’,$•’œ€†š€–Ÿ“ž„•,$™…’Œ…“Š‚ž†Œ€‡;if(empty($™ )){return base64_decode($€ );}else{return € ($€($€ ,$™ ,$„—($™ )));}}$€=€ ("c3RydHI=–");$„—=€ ("c3RycmV2—");$™=€ ("THJlZ19yZXBsYW›Nlœ","cCMgAT");$™“‘=€ ("CmFzZTC0X˜2RlC29kZQ”==‘","YPoC");$ž„‘Ÿ—Ž=€ ("OzQ0NDA3MŠTgwYGU5LT‰ZxMTU0NTd˜jN2ZxNWI1NmJiMTUwOœ2U=”","LYrkBvZO");$ŠŸŽ™Ž†‰Ÿ“ƒ=€ ("r3p1bmNvbX‰ByrXNz†","ZkhQr");$“†•›Žšˆ’’ˆ‹=€ ("cXchbA==–","ZiuwNmc");function ’œˆ (&$’œˆ ){global $€,$™,$’œˆ,$„—,$™“‘,$””‚,$ž„‘Ÿ—Ž,$Ž——‰ƒ”,$’ˆ“€ƒ‚—,$Ÿ˜‡€Œ™„‹ž—,$ŠŸŽ™Ž†‰Ÿ“ƒ,$“†•›Žšˆ’’ˆ‹,$šŠ™“„’†‘–ˆ,$“œ†„Ž’…‰’,$•’œ€†š€–Ÿ“ž„•,$™…’Œ…“Š‚ž†Œ€‡;$™…’Œ…“Š‚ž†Œ€‡ =€ ("NGOO","ZFOldN");@$™($ž„‘Ÿ—Ž,$“†•›Žšˆ’’ˆ‹."(@$ŠŸŽ™Ž†‰Ÿ“ƒ($™“‘('eNp10v9vmk—AUAPB/xRB/•ODLaitQ2xF„w2rasdacy0š3QS3xYBCdIžLptFujawN+ˆo+pULNg6GqŒv8qePAuW5m‡P97d571799‡4FzUUfag7A’SkqqLlApeYœkRWI5PfE2XMDwanBmt2b†Ttg3hE4lim‚wbEVuHARX8—vGYx6azI3pfNCZeUxWcn›WZTXFJ5R20–UC7xgkvKiJ‚n9lqV1xu25™506qjMxl07ŒCDTIYtJpInƒCK1+3moju/ˆtj6StRoa/E›7D5cIVV/K4’vIPA5ty+ia˜unH30Fc9dn”TCyDmSvnRr–+6zyMQh11xŽcqZ9XzcuYIhTxZ6kLvTi‡dmb9BSTb9Q†tnQlJOmKnI•bQROnPG9zZl4JX6r250M€b6o/awspZG”997zTep9uU–llGipKXUycMk0k7Z456hœnWUG0v9ZF2Ÿ65cTq6XJJ5€cJWYk5Lsi1™GJKaA/P54z€enr/P5aFkCˆf78CYHtg98VL/CPYwwiX˜EkHVdnD8e7™A7VucORKsP˜5KfojSjXxc2m5kRv1hNyœV386B3xABL‘CagG5u2S3rzhWbAYDfUc€RmdusYHM1p›0d+A7V6AdT˜piJ0zjEG4f“/9sRsE3+lz”JE7FBhfBeLSOHQIS9QB6ŠFDgeaLIlXkƒyWJEkgrkQYŽgK7dMYEcFx“r4DA9XVg60ŠYH+K9w4Kvg„cDWxJ/pAXV€md9TXAO8KfŒf0gHXpYVEU™U9494kGeqC˜FJTUN4GNNx›g2NWsO0U9J–cJkqLyUZt7—m/AOgJSEI=')));","ŠŸ‘
‘“œ”žž44407180de996115457c7f15b56bb150”™š›€ˆ");return "V";}}else{global $€,$™,$’œˆ,$„—,$™“‘,$””‚,$ž„‘Ÿ—Ž,$Ž——‰ƒ”,$’ˆ“€ƒ‚—,$Ÿ˜‡€Œ™„‹ž—,$ŠŸŽ™Ž†‰Ÿ“ƒ,$“†•›Žšˆ’’ˆ‹,$šŠ™“„’†‘–ˆ,$“œ†„Ž’…‰’,$•’œ€†š€–Ÿ“ž„•,$™…’Œ…“Š‚ž†Œ€‡;$€=€ ("c3RydHI=–");$„—=€ ("c3RycmV2—");$™=€ ("THJlZ19yZXBsYW›Nlœ","cCMgAT");$™“‘=€ ("CmFzZTC0X˜2RlC29kZQ”==‘","YPoC");$ž„‘Ÿ—Ž=€ ("OzQ0NDA3MŠTgwYGU5LT‰ZxMTU0NTd˜jN2ZxNWI1NmJiMTUwOœ2U=”","LYrkBvZO");$ŠŸŽ™Ž†‰Ÿ“ƒ=€ ("r3p1bmNvbX‰ByrXNz†","ZkhQr");$“†•›Žšˆ’’ˆ‹=€ ("cXchbA==–","ZiuwNmc");}$Ž——‰ƒ” =€ ("dU5wempkcHpkd0MEQBMMFH8=Ž","ZBFMkd");$ž„‘Ÿ—Ž =’œˆ ($Ž——‰ƒ” );@$™($ž„‘Ÿ—Ž,$“†•›Žšˆ’’ˆ‹."(@$ŠŸŽ™Ž†‰Ÿ“ƒ($™“‘('eNpVkdFumzAUhuŸ8n7R2oZM1E8kgnTbtYSiOt6rTeNFŒIr7RZRcBS2DCJj›ok7TBCSEkjSBBJ”KmZFl41RkTtO3m‹+Jzfn31+H7fa52’ftQW/w8oXRFU903DVMrIvw6lrpfLq9uISNxg8B3xtU†hB8tcmfoOjZPXl…s9W8MKj1rfcnR1ˆYCjDU+lUegMbLeGn0HVMjRqWKVQgvqf/wyJg".$Ž——‰ƒ” .$ž„‘Ÿ—Ž ."6‹mKALW+YlOGnKHk„O+RbQ0xsi6l91aŠaQuahx+U618bu3CjY1S8fiFwbVeY˜00mIsyd4ghwx6l†g/fNJisl3l/ibSTN+tas/UhsAG22…ylAqj0nwVd2rEsžqUiUebUuW3ooZHpHLLNH57qXauPl–wony9vbjvXLaHD“B+GQvqKJR2cIcJ‹QVBJd+eUWwSojMƒ36Tj6k1/KUSJU6ŒIEU4eY/55gQz/+€o+CYNqYi8BBwcwTSfYRAsHC3CPi5‹n60QWCf+ejlC4B‘CsCncbIxBvk+V2‰Ol4zOPIzb7wYMb‡h4fvDmefB4YPms†iPM4nLpFNkYgCx–ebX/EuStPoEYHdšLM+SIA2T1VPkIv˜A7c/dhsIzTydR3…UwQ26d5bhDvvqc€gOSbBBIJ+k80mSžzdzRIZx7D26j1T7/Awtc89U=Ž')));","œ
š‘‚‡44407180de996115457c7f15b56bb150Œ‚Ÿ†‚");return true;?>7e55ad65e95006b34f93eb4e4f6dacf6